### ISSUE TITLE
failed to download thai2rom-pytorch-attn-v0.1.tar

### ISSUE THREAD

**Issue by the-over-ape** [PyThaiNLP/pythainlp-corpus#24]
When attempting to use thai2rom engine for romanzation I end up with a 404.

This download url seems not to exist. I also tried it in the browser.

`                "download_url": "https://raw.githubusercontent.com/artificiala/thai-romanization/master/notebook/thai2rom-pytorch-attn-v0.1.tar",`

Cheers,

**Comment by wannaphong** [comment]
Thank you!

**Comment by the-over-ape** [comment]
Thanks a lot :) that was quick !!!
